CREATE DATABASE CB_LAB;

USE CB_LAB;


IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_GUESTCHECKS' AND xtype='U')
CREATE TABLE TB_GUESTCHECKS (
	GUESTCHECK_ID BIGINT PRIMARY KEY,
	CHKNUM INT, -- N�mero da conta
	OPNSBUSDT DATE, -- Data de abertura da conta
	OPNUTC DATETIME, -- Data de abertura da conta e hora UTC
	OPNLCL DATETIME, -- Data de abertura da conta e hora local
	CLSDBUSTD DATE, -- Data do fechamento
	CLSDUTC DATETIME, -- Data e hor�rio do fechamento UTC
	CLSDLCL DATETIME, -- Data e hor�rio do fechamento local
	LASTTRANSLCL DATETIME,
	LASTTRANSUTC DATETIME,
	LASTUPDATEDLCL DATETIME,
	LASTUPDATEDUTC DATETIME,
	CLSDFLAG BIT DEFAULT 0, -- Ajustado BOOL para BIT
	GSTCNT INT,
	SUBTTL DECIMAL(10,2),
	NONTXBLSLSTTL DECIMAL(10,2),
	CHKTTL DECIMAL(10,2),
	DSCTTL DECIMAL(10,2),
	PAYTTL DECIMAL(10,2),
	BALDUETTL DECIMAL(10,2),
	RVCNUM INT,
	OTNUM INT,
	OCNUM INT NULL,
	TBLNUM BIGINT NOT NULL,
	TBLNAME BIGINT NOT NULL,
	EMPNUM INT NOT NULL,
	NUMSRVCRD INT NOT NULL,
	NUMCHKPRNTD INT NOT NULL
);

-- Tabela TB_TAXES
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_TAXES' AND xtype='U')
CREATE TABLE TB_TAXES (
	TAXE_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	TAXNUM INT NOT NULL,
	TXBLSLSTTL DECIMAL(10,2),
	TAXCOLLTTL DECIMAL(10,2),
	TAXRATE DECIMAL(10,2),
	TYPE INT,
	GUESTCHECK_ID_FK BIGINT NOT NULL,
	FOREIGN KEY (GUESTCHECK_ID_FK) REFERENCES TB_GUESTCHECKS(GUESTCHECK_ID)
);

-- Tabela TB_DETAILINES
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_DETAILINES' AND xtype='U')
CREATE TABLE TB_DETAILINES (
	DETAILLINE_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	GUESTCHECKLINE_ID BIGINT NOT NULL,
	RVCNUM INT,
	DTLOTNUM INT,
	LINENUM INT NOT NULL,
	DETAILUTC DATETIME,
	DETAILLCL DATETIME,
	DSPTLL DECIMAL(10,2),
	DSPQTY INT,
	AGGTLT DECIMAL(10,2),
	AGGQTY INT,
	CHKEMPID BIGINT NOT NULL,
	CHKEMPNUM INT,
	SVCRNDNUM INT,
	SEATNUM INT,
	GUESTCHECK_ID_FK BIGINT NOT NULL,
	FOREIGN KEY (GUESTCHECK_ID_FK) REFERENCES TB_GUESTCHECKS(GUESTCHECK_ID)
);

-- Tabela TB_MENUITEM
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_MENUITEM' AND xtype='U')
CREATE TABLE TB_MENUITEM (
	MENUITEM_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	MINUM INT NOT NULL,
	MODFLAG BIT DEFAULT 0, -- Ajustado BOOL para BIT
	INCITAX DECIMAL(10,2),
	ACTIVETAXES INT,
	PRCLVL INT,
	DETAILLINE_ID_FK BIGINT,
	FOREIGN KEY (DETAILLINE_ID_FK) REFERENCES TB_DETAILINES(DETAILLINE_ID)
);

-- Tabela TB_DISCOUNT
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_DISCOUNT' AND xtype='U')
CREATE TABLE TB_DISCOUNT (
	DISCOUNT_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	VALUE DECIMAL(10,2),
	GUESTCHECKLINEITEM_ID_FK BIGINT,
	FOREIGN KEY (GUESTCHECKLINEITEM_ID_FK) REFERENCES TB_DETAILINES(DETAILLINE_ID)
);

-- Tabela TB_TYPE_DISCOUNT
-- Esta tabela foi projetada para categorizar os tipos  de desconto de forma at�mica. Ela permite mapear diferentes categorias de descontos (como "tempo de atraso de atendimento", "cobran�a indevida", etc.)
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_TYPE_DISCOUNT' AND xtype='U')
CREATE TABLE TB_TYPE_DISCOUNT (
	TYPE_DISCOUNT_ID SMALLINT IDENTITY(1,1) PRIMARY KEY,
	REASON VARCHAR(255),
	DISCOUNT_ID_FK BIGINT,
	FOREIGN KEY (DISCOUNT_ID_FK) REFERENCES TB_DISCOUNT(DISCOUNT_ID)
);

-- Tabela TB_SERVICECHARGE
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_SERVICECHARGE' AND xtype='U')
CREATE TABLE TB_SERVICECHARGE (
	SERVICECHARGE_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	CHARGENAME VARCHAR(255),
	VALUE DECIMAL(10,2),
	GUESTCHECKLINEITEM_ID_FK BIGINT,
	FOREIGN KEY (GUESTCHECKLINEITEM_ID_FK) REFERENCES TB_DETAILINES(DETAILLINE_ID)
);

-- Tabela TB_TENDERMEDIA
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_TENDERMEDIA' AND xtype='U')
CREATE TABLE TB_TENDERMEDIA (
	TENDERMEDIA_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
	VALUE DECIMAL(10,2),
	GUESTCHECKLINEITEM_ID_FK BIGINT,
	FOREIGN KEY (GUESTCHECKLINEITEM_ID_FK) REFERENCES TB_DETAILINES(DETAILLINE_ID)
);

-- Tabela TB_TYPE_TENDERMEDIA
-- Esta tabela foi projetada para categorizar os tipos de m�todos de pagamento de forma at�mica. Ela permite mapear diferentes categorias de pagamentos (como "Cart�o de Cr�dito", "Dinheiro", etc.)
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_TYPE_TENDERMEDIA' AND xtype='U')
CREATE TABLE TB_TYPE_TENDERMEDIA (
	TYPE_TENDERMEDIA_ID SMALLINT IDENTITY(1,1) PRIMARY KEY,
	PAYMENT_TYPE VARCHAR(255),
	TENDERMEDIA_ID_FK BIGINT,
	FOREIGN KEY (TENDERMEDIA_ID_FK) REFERENCES TB_TENDERMEDIA(TENDERMEDIA_ID)
);

-- Tabela TB_ERRORCODE
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_ERRORCODE' AND xtype='U')
CREATE TABLE TB_ERRORCODE (
	ERRORCODE_ID SMALLINT IDENTITY(1,1) PRIMARY KEY,
	INFORMATIVE VARCHAR(255),
	GUESTCHECKLINEITEM_ID_FK BIGINT,
	FOREIGN KEY (GUESTCHECKLINEITEM_ID_FK) REFERENCES TB_DETAILINES(DETAILLINE_ID)
);

-- Tabela TB_TYPE_ERRORCODE
-- Esta tabela foi projetada para categorizar os tipos de m�todos de falha no sistema ou fluxo de forma at�mica. Ela permite mapear diferentes categorias de erros (como "Tempo de reposta", "Falha ao tempo de pagamento", etc.)
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='TB_TYPE_ERRORCODE' AND xtype='U')
CREATE TABLE TB_TYPE_ERRORCODE (
	TYPE_DISCOUNT_ID SMALLINT IDENTITY(1,1) PRIMARY KEY,
	DESCRIPTION VARCHAR(255),
	ERRORCODE_ID_FK SMALLINT,
	MESSAGE VARCHAR(255),
	FOREIGN KEY (ERRORCODE_ID_FK) REFERENCES TB_ERRORCODE(ERRORCODE_ID)
);
